language: python
python:
  - "3.5"
install:
  - pip install coveralls
  - pip install nose
# command to run tests
script:
  nosetests -v --with-coverage --cover-package thor test/test_*.py
after_success:
  coveralls
