version: 2
jobs:
  "Python 3.5":
    working_directory: ~/thor
    docker:
      - image: circleci/python:3.5.6
    steps:
      - checkout
      - run:
          name: install-requirements
          command: pip install --user coveralls nose2
      - run:
          name: test
          command: ~/.local/bin/nose2 -v --with-coverage

  "Python 3.6":
    working_directory: ~/thor
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install-requirements
          command: pip install --user coveralls nose2
      - run:
          name: test
          command: ~/.local/bin/nose2 -v --with-coverage

  "Python 3.7":
    working_directory: ~/thor
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install-requirements
          command: pip install --user coveralls nose2
      - run:
          name: test
          command: ~/.local/bin/nose2 -v --with-coverage

workflows:
  version: 2
  build:
    jobs:
      - "Python 3.5"
      - "Python 3.6"
      - "Python 3.7"
